[nixpacks]
providers = ["node", "apt"]
nodeVersion = "22"

[apt]
packages = ["libcairo2-dev", "libpango1.0-dev", "libjpeg-dev", "libgif-dev", "librsvg2-dev", "fonts-noto", "libpixman-1-dev", "libfreetype6-dev", "build-essential"]

[phases.setup]
cmds = ["apt-get update -qq"]

[phases.install]
cmds = ["npm install --legacy-peer-deps --ignore-engines"]

[start]
cmd = "node index.js"