[nixpacks]
providers = ["node", "apt"]

[apt]
packages = ["libcairo2-dev", "libpango1.0-dev", "libjpeg-dev", "libgif-dev", "librsvg2-dev"]

[phases.setup]
cmds = ["apt-get update -qq"]

[start]
cmd = "node index.js"
